fix/append-managementportal-to-baseurl
RADAR-base/ManagementPortal pull request #733
Opened 2023-10-04 10:26 UTC by Bdegraaf1234

No more rerouting in the Angular live development server (ALDS). server.servlet.context-path and managementportal.common.managementportalbaseurl changed in dev to match prod.

Description: change application-dev.properties to more closely match application-prod.properties and revisit some changes made in #725 

Fixes #732

#### Checklist:
- [ ] The [Main workflow](https://github.com/RADAR-base/ManagementPortal/actions/workflows/main.yml) has succeeded
- [ ] The [Gatling tests](https://github.com/RADAR-base/ManagementPortal#other-tests) have passed
- [ ] I have logged into the portal running locally with default admin credentials
- [ ] I have updated the README files if this change requires documentation update
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-10-04 10:33 UTC, Bdegraaf1234 commented
this is a working setup but still needs the ALDS to handle the /magementportal/oauth/* requests.

did not look at the double `/` issue yet

2023-10-04 11:10 UTC, blootsvoets reviewed
Also this would need the new base href value: https://github.com/RADAR-base/ManagementPortal/blob/67403f8e93f2570b754cd1b7e027ea3b15276e3d/src/main/webapp/index.html#L4

2023-10-04 12:34 UTC, Bdegraaf1234 commented on src/main/resources/config/application-dev.yml
> +        baseUrl: http://localhost:8081 # Modify according to your server's URL
changes here do not seem to affect anything, but it was a mismatch between the angular dev server port after changes in #725 so I set it to match again

2023-10-04 12:37 UTC, Bdegraaf1234 commented on src/main/resources/config/application-dev.yml
> +        managementPortalBaseUrl: http://localhost:8080/managementportal
The lack of trailing / should fix the broken meta-token url

2023-10-04 13:03 UTC, blootsvoets approved these changes

2023-10-04 13:06 UTC, blootsvoets requested changes
I see that the gatling tests are still referring to the old URL. Please update those as well. See `src/gatling/scala/ManagementPortalSimulation`

2023-10-05 14:43 UTC, Bdegraaf1234 commented on src/main/resources/config/application-dev.yml
> +        baseUrl: http://localhost:8081 # Modify according to your server's URL
indeed, just used for building mail and metatokens

2023-10-06 11:48 UTC, Bdegraaf1234 commented
It seems like the current production builds are not compatible with an ALDS proxy/frontend due to the addition of the `/managementportal/` context-path.

There is an authentication problem when using accessing via a front-end (cypress, ALDS), the token is successfully retrieved but not attached to the subsequent requests (specifically, `/api/organizations` and `/api/projects`).

The problem is over my head at this point, but I think it is related to #717 as it prevents us from running cypress tests on a production environment. I cannot find any place where this [script](https://github.com/RADAR-base/ManagementPortal/blob/master/src/test/bash/run-prod-e2e.sh) which should achieve this is ran.

2023-10-06 12:56 UTC, blootsvoets commented
Perhaps two proxy config are needed then — one with path rewrite and one without?

2023-10-06 15:03 UTC, Bdegraaf1234 commented
I think the proxy stuff was a bit of red herring, it really was a problem with the cookie not propagating somehow.

I now manually set the path of the cookie to `/` (mirroring the situation we have in the k3s-test deployment). This ensures that all requests belong to the same session, and the authentication works again.

I think we should now be able to run the e2e tests on a production build and remove quite a few distinct commands between dev and prod builds.

2023-10-06 16:08 UTC, Bdegraaf1234 commented
Ready for review.

Ran the e2e tests on a local production build, 2 failing tests. Will make a branch for #717 to pick this up next week.

2023-10-09 07:49 UTC, blootsvoets reviewed
Looks good, nice that you got it fixed! Some small notes.

2023-10-09 07:49 UTC, blootsvoets commented on src/test/bash/run-prod-e2e.sh
>  yarn run wait-for-managementportal-prod
Should be `wait-for-managementportal`

2023-10-09 07:49 UTC, blootsvoets commented on src/main/docker/Dockerfile
> +FROM eclipse-temurin:17-jdk
Since nothing is built in the docker file, this can be `eclipse-temurin:17-jre`

2023-10-09 11:33 UTC, blootsvoets approved these changes
LGTM

2023-10-09 11:34 UTC, merged